// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { CodecTypes as IdbCodecTypes } from "@prisma-idb/target-idb/pack";

import type { IdbContractWithTypeMaps, IdbTypeMaps } from "@prisma-idb/target-idb/pack";
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from "@prisma/orm-postgres/contract/types";

export type StorageHash = StorageHashBase<"f57f9cb96b36d6251be55bf297614dd74dab0861b6f77b83991c0dca40ca59dd">;
export type ExecutionHash = ExecutionHashBase<"1ccd214e2c572bf6e165a7da549585dba6d39694a151e2695a9109ed7899d4dd">;
export type ProfileHash = ProfileHashBase<"40329830af4e39e0774683fbebcdc24dcf983a5da02c5fe6079a2a57579f861c">;

export type CodecTypes = IdbCodecTypes;
export type LaneCodecTypes = CodecTypes;

export type FieldOutputTypes = {
  readonly __unbound__: {
    readonly Board: {
      readonly id: CodecTypes["idb/string@1"]["output"];
      readonly name: CodecTypes["idb/string@1"]["output"];
      readonly createdAt: CodecTypes["idb/date@1"]["output"];
      readonly userId: CodecTypes["idb/string@1"]["output"];
    };
    readonly Todo: {
      readonly id: CodecTypes["idb/string@1"]["output"];
      readonly title: CodecTypes["idb/string@1"]["output"];
      readonly description: CodecTypes["idb/string@1"]["output"] | null;
      readonly isCompleted: CodecTypes["idb/bool@1"]["output"];
      readonly createdAt: CodecTypes["idb/date@1"]["output"];
      readonly boardId: CodecTypes["idb/string@1"]["output"];
    };
    readonly User: {
      readonly id: CodecTypes["idb/string@1"]["output"];
      readonly name: CodecTypes["idb/string@1"]["output"];
      readonly email: CodecTypes["idb/string@1"]["output"];
      readonly emailVerified: CodecTypes["idb/bool@1"]["output"];
      readonly image: CodecTypes["idb/string@1"]["output"] | null;
      readonly createdAt: CodecTypes["idb/date@1"]["output"];
      readonly updatedAt: CodecTypes["idb/date@1"]["output"];
      readonly isAnonymous: CodecTypes["idb/bool@1"]["output"];
    };
  };
};
export type FieldInputTypes = {
  readonly __unbound__: {
    readonly Board: {
      readonly id: CodecTypes["idb/string@1"]["input"];
      readonly name: CodecTypes["idb/string@1"]["input"];
      readonly createdAt: CodecTypes["idb/date@1"]["input"];
      readonly userId: CodecTypes["idb/string@1"]["input"];
    };
    readonly Todo: {
      readonly id: CodecTypes["idb/string@1"]["input"];
      readonly title: CodecTypes["idb/string@1"]["input"];
      readonly description: CodecTypes["idb/string@1"]["input"] | null;
      readonly isCompleted: CodecTypes["idb/bool@1"]["input"];
      readonly createdAt: CodecTypes["idb/date@1"]["input"];
      readonly boardId: CodecTypes["idb/string@1"]["input"];
    };
    readonly User: {
      readonly id: CodecTypes["idb/string@1"]["input"];
      readonly name: CodecTypes["idb/string@1"]["input"];
      readonly email: CodecTypes["idb/string@1"]["input"];
      readonly emailVerified: CodecTypes["idb/bool@1"]["input"];
      readonly image: CodecTypes["idb/string@1"]["input"] | null;
      readonly createdAt: CodecTypes["idb/date@1"]["input"];
      readonly updatedAt: CodecTypes["idb/date@1"]["input"];
      readonly isAnonymous: CodecTypes["idb/bool@1"]["input"];
    };
  };
};
export type TypeMaps = IdbTypeMaps<CodecTypes, FieldOutputTypes, FieldInputTypes>;

type ContractBase = Omit<
  ContractType<{
    readonly stores: {
      readonly board: {
        readonly keyPath: "id";
        readonly indexes: {
          readonly userId: { readonly keyPath: "userId"; readonly unique: false };
        };
      };
      readonly todo: {
        readonly keyPath: "id";
        readonly indexes: {
          readonly boardId: { readonly keyPath: "boardId"; readonly unique: false };
        };
      };
      readonly user: {
        readonly keyPath: "id";
        readonly indexes: {
          readonly email_unique: { readonly keyPath: "email"; readonly unique: true };
        };
      };
    };
    readonly namespaces: {
      readonly __unbound__: { readonly id: "__unbound__"; readonly entries: Record<string, never> };
    };
    readonly storageHash: StorageHash;
  }>,
  "roots" | "domain"
> & {
  readonly target: "idb";
  readonly targetFamily: "idb";
  readonly roots: {
    readonly user: { readonly namespace: "__unbound__" & NamespaceId; readonly model: "User" };
    readonly board: { readonly namespace: "__unbound__" & NamespaceId; readonly model: "Board" };
    readonly todo: { readonly namespace: "__unbound__" & NamespaceId; readonly model: "Todo" };
  };
  readonly domain: {
    readonly namespaces: {
      readonly __unbound__: {
        readonly models: {
          readonly Board: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/date@1" };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
              };
            };
            readonly relations: {
              readonly user: {
                readonly to: {
                  readonly namespace: "__unbound__" & NamespaceId;
                  readonly model: "User";
                };
                readonly cardinality: "N:1";
                readonly on: {
                  readonly localFields: readonly ["userId"];
                  readonly targetFields: readonly ["id"];
                };
              };
              readonly todos: {
                readonly to: {
                  readonly namespace: "__unbound__" & NamespaceId;
                  readonly model: "Todo";
                };
                readonly cardinality: "1:N";
                readonly on: {
                  readonly localFields: readonly ["id"];
                  readonly targetFields: readonly ["boardId"];
                };
              };
            };
            readonly storage: { readonly storeName: "board"; readonly keyPath: "id" };
          };
          readonly Todo: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
              };
              readonly title: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
              };
              readonly description: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
              };
              readonly isCompleted: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/bool@1" };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/date@1" };
              };
              readonly boardId: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
              };
            };
            readonly relations: {
              readonly board: {
                readonly to: {
                  readonly namespace: "__unbound__" & NamespaceId;
                  readonly model: "Board";
                };
                readonly cardinality: "N:1";
                readonly on: {
                  readonly localFields: readonly ["boardId"];
                  readonly targetFields: readonly ["id"];
                };
              };
            };
            readonly storage: { readonly storeName: "todo"; readonly keyPath: "id" };
          };
          readonly User: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
              };
              readonly emailVerified: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/bool@1" };
              };
              readonly image: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/date@1" };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/date@1" };
              };
              readonly isAnonymous: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/bool@1" };
              };
            };
            readonly relations: {
              readonly boards: {
                readonly to: {
                  readonly namespace: "__unbound__" & NamespaceId;
                  readonly model: "Board";
                };
                readonly cardinality: "1:N";
                readonly on: {
                  readonly localFields: readonly ["id"];
                  readonly targetFields: readonly ["userId"];
                };
              };
            };
            readonly storage: { readonly storeName: "user"; readonly keyPath: "id" };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly idb: {
      readonly compoundKeys: false;
      readonly ddlOnlyInUpgrade: true;
      readonly returning: false;
      readonly transactionalDDL: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: "__unbound__";
            readonly table: "user";
            readonly column: "emailVerified";
          };
          readonly onCreate: {
            readonly kind: "generator";
            readonly id: "literal";
            readonly params: { readonly value: false };
          };
        },
        {
          readonly ref: {
            readonly namespace: "__unbound__";
            readonly table: "user";
            readonly column: "createdAt";
          };
          readonly onCreate: { readonly kind: "generator"; readonly id: "timestampNow" };
        },
        {
          readonly ref: {
            readonly namespace: "__unbound__";
            readonly table: "user";
            readonly column: "isAnonymous";
          };
          readonly onCreate: {
            readonly kind: "generator";
            readonly id: "literal";
            readonly params: { readonly value: false };
          };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = IdbContractWithTypeMaps<ContractBase, TypeMaps>;

export type Stores = Contract["storage"]["stores"];
