// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { CodecTypes as IdbCodecTypes } from "@prisma-idb/target-idb/pack";

import type { IdbContractWithTypeMaps, IdbTypeMaps } from "@prisma-idb/target-idb/pack";
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from "@prisma/orm-framework/contract/types";

export type StorageHash = StorageHashBase<"fc8ba5682814d9f05d17d2e547a2e1f6d261bd40be8b43ae981e5880717c57ee">;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash = ProfileHashBase<"40329830af4e39e0774683fbebcdc24dcf983a5da02c5fe6079a2a57579f861c">;

export type CodecTypes = IdbCodecTypes;
export type LaneCodecTypes = CodecTypes;

export type FieldOutputTypes = {
  readonly __unbound__: {
    readonly Post: {
      readonly id: CodecTypes["idb/string@1"]["output"];
      readonly title: CodecTypes["idb/string@1"]["output"];
      readonly content: CodecTypes["idb/string@1"]["output"] | null;
      readonly published: CodecTypes["idb/bool@1"]["output"];
      readonly views: CodecTypes["idb/int32@1"]["output"];
      readonly authorId: CodecTypes["idb/string@1"]["output"];
      readonly createdAt: CodecTypes["idb/date@1"]["output"];
    };
    readonly RandomStore: { readonly id: CodecTypes["idb/string@1"]["output"] };
    readonly Tag: {
      readonly id: CodecTypes["idb/string@1"]["output"];
      readonly name: CodecTypes["idb/string@1"]["output"];
      readonly postId: CodecTypes["idb/string@1"]["output"];
    };
    readonly User: {
      readonly id: CodecTypes["idb/string@1"]["output"];
      readonly name: CodecTypes["idb/string@1"]["output"];
      readonly email: CodecTypes["idb/string@1"]["output"];
      readonly bio: CodecTypes["idb/string@1"]["output"] | null;
      readonly score: CodecTypes["idb/int32@1"]["output"];
      readonly active: CodecTypes["idb/bool@1"]["output"];
      readonly joinedAt: CodecTypes["idb/date@1"]["output"];
    };
  };
};
export type FieldInputTypes = {
  readonly __unbound__: {
    readonly Post: {
      readonly id: CodecTypes["idb/string@1"]["input"];
      readonly title: CodecTypes["idb/string@1"]["input"];
      readonly content: CodecTypes["idb/string@1"]["input"] | null;
      readonly published: CodecTypes["idb/bool@1"]["input"];
      readonly views: CodecTypes["idb/int32@1"]["input"];
      readonly authorId: CodecTypes["idb/string@1"]["input"];
      readonly createdAt: CodecTypes["idb/date@1"]["input"];
    };
    readonly RandomStore: { readonly id: CodecTypes["idb/string@1"]["input"] };
    readonly Tag: {
      readonly id: CodecTypes["idb/string@1"]["input"];
      readonly name: CodecTypes["idb/string@1"]["input"];
      readonly postId: CodecTypes["idb/string@1"]["input"];
    };
    readonly User: {
      readonly id: CodecTypes["idb/string@1"]["input"];
      readonly name: CodecTypes["idb/string@1"]["input"];
      readonly email: CodecTypes["idb/string@1"]["input"];
      readonly bio: CodecTypes["idb/string@1"]["input"] | null;
      readonly score: CodecTypes["idb/int32@1"]["input"];
      readonly active: CodecTypes["idb/bool@1"]["input"];
      readonly joinedAt: CodecTypes["idb/date@1"]["input"];
    };
  };
};
export type TypeMaps = IdbTypeMaps<CodecTypes, FieldOutputTypes, FieldInputTypes>;

type ContractBase = Omit<
  ContractType<{
    readonly stores: {
      readonly posts: {
        readonly keyPath: "id";
        readonly indexes: {
          readonly byAuthorId: { readonly keyPath: "authorId"; readonly unique: false };
        };
      };
      readonly random_store: { readonly keyPath: "id"; readonly indexes: Record<string, never> };
      readonly tags: {
        readonly keyPath: "id";
        readonly indexes: {
          readonly byPostId: { readonly keyPath: "postId"; readonly unique: false };
        };
      };
      readonly users: {
        readonly keyPath: "id";
        readonly indexes: {
          readonly byEmail: { readonly keyPath: "email"; readonly unique: true };
          readonly byScore: { readonly keyPath: "score"; readonly unique: false };
        };
      };
    };
    readonly namespaces: {
      readonly __unbound__: { readonly id: "__unbound__"; readonly entries: Record<string, never> };
    };
    readonly storageHash: StorageHash;
  }>,
  "roots" | "domain"
> & {
  readonly target: "idb";
  readonly targetFamily: "idb";
  readonly roots: {
    readonly users: { readonly namespace: "__unbound__" & NamespaceId; readonly model: "User" };
    readonly posts: { readonly namespace: "__unbound__" & NamespaceId; readonly model: "Post" };
    readonly tags: { readonly namespace: "__unbound__" & NamespaceId; readonly model: "Tag" };
    readonly random_store: {
      readonly namespace: "__unbound__" & NamespaceId;
      readonly model: "RandomStore";
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly __unbound__: {
        readonly models: {
          readonly Post: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
              };
              readonly title: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
              };
              readonly content: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
              };
              readonly published: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/bool@1" };
              };
              readonly views: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/int32@1" };
              };
              readonly authorId: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/date@1" };
              };
            };
            readonly relations: {
              readonly author: {
                readonly to: {
                  readonly namespace: "__unbound__" & NamespaceId;
                  readonly model: "User";
                };
                readonly cardinality: "N:1";
                readonly on: {
                  readonly localFields: readonly ["authorId"];
                  readonly targetFields: readonly ["id"];
                };
              };
              readonly tags: {
                readonly to: {
                  readonly namespace: "__unbound__" & NamespaceId;
                  readonly model: "Tag";
                };
                readonly cardinality: "1:N";
                readonly on: {
                  readonly localFields: readonly ["id"];
                  readonly targetFields: readonly ["postId"];
                };
              };
            };
            readonly storage: { readonly storeName: "posts"; readonly keyPath: "id" };
          };
          readonly RandomStore: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly storeName: "random_store"; readonly keyPath: "id" };
          };
          readonly Tag: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
              };
              readonly postId: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
              };
            };
            readonly relations: {
              readonly post: {
                readonly to: {
                  readonly namespace: "__unbound__" & NamespaceId;
                  readonly model: "Post";
                };
                readonly cardinality: "N:1";
                readonly on: {
                  readonly localFields: readonly ["postId"];
                  readonly targetFields: readonly ["id"];
                };
              };
            };
            readonly storage: { readonly storeName: "tags"; readonly keyPath: "id" };
          };
          readonly User: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
              };
              readonly bio: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
              };
              readonly score: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/int32@1" };
              };
              readonly active: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/bool@1" };
              };
              readonly joinedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/date@1" };
              };
            };
            readonly relations: {
              readonly posts: {
                readonly to: {
                  readonly namespace: "__unbound__" & NamespaceId;
                  readonly model: "Post";
                };
                readonly cardinality: "1:N";
                readonly on: {
                  readonly localFields: readonly ["id"];
                  readonly targetFields: readonly ["authorId"];
                };
              };
            };
            readonly storage: { readonly storeName: "users"; readonly keyPath: "id" };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly idb: {
      readonly compoundKeys: false;
      readonly ddlOnlyInUpgrade: true;
      readonly returning: false;
      readonly transactionalDDL: true;
    };
  };
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = IdbContractWithTypeMaps<ContractBase, TypeMaps>;

export type Stores = Contract["storage"]["stores"];
