// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { CodecTypes as IdbCodecTypes } from "@prisma-idb/target-idb/pack";

import type { IdbContractWithTypeMaps, IdbTypeMaps } from "@prisma-idb/target-idb/pack";
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from "@prisma/orm-framework/contract/types";

export type StorageHash = StorageHashBase<"c2c485fabf1d79f78fdaf74a1c4dd94fe4e3981493233534e003c613f643945d">;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash = ProfileHashBase<"40329830af4e39e0774683fbebcdc24dcf983a5da02c5fe6079a2a57579f861c">;

export type CodecTypes = IdbCodecTypes;
export type LaneCodecTypes = CodecTypes;

export type FieldOutputTypes = {
  readonly __unbound__: {
    readonly OutboxEvent: {
      readonly id: CodecTypes["idb/string@1"]["output"];
      readonly entityType: CodecTypes["idb/string@1"]["output"];
      readonly operation: CodecTypes["idb/string@1"]["output"];
      readonly payload: CodecTypes["idb/json@1"]["output"];
      readonly createdAt: CodecTypes["idb/date@1"]["output"];
      readonly synced: CodecTypes["idb/bool@1"]["output"];
      readonly syncedAt: CodecTypes["idb/date@1"]["output"] | null;
      readonly lastAttemptedAt: CodecTypes["idb/date@1"]["output"] | null;
      readonly tries: CodecTypes["idb/int32@1"]["output"];
      readonly lastError: CodecTypes["idb/string@1"]["output"] | null;
      readonly retryable: CodecTypes["idb/bool@1"]["output"];
    };
    readonly VersionMeta: {
      readonly id: CodecTypes["idb/string@1"]["output"];
      readonly model: CodecTypes["idb/string@1"]["output"];
      readonly key: CodecTypes["idb/json@1"]["output"];
      readonly lastAppliedChangeId: CodecTypes["idb/string@1"]["output"] | null;
      readonly localChangePending: CodecTypes["idb/bool@1"]["output"];
    };
  };
};
export type FieldInputTypes = {
  readonly __unbound__: {
    readonly OutboxEvent: {
      readonly id: CodecTypes["idb/string@1"]["input"];
      readonly entityType: CodecTypes["idb/string@1"]["input"];
      readonly operation: CodecTypes["idb/string@1"]["input"];
      readonly payload: CodecTypes["idb/json@1"]["input"];
      readonly createdAt: CodecTypes["idb/date@1"]["input"];
      readonly synced: CodecTypes["idb/bool@1"]["input"];
      readonly syncedAt: CodecTypes["idb/date@1"]["input"] | null;
      readonly lastAttemptedAt: CodecTypes["idb/date@1"]["input"] | null;
      readonly tries: CodecTypes["idb/int32@1"]["input"];
      readonly lastError: CodecTypes["idb/string@1"]["input"] | null;
      readonly retryable: CodecTypes["idb/bool@1"]["input"];
    };
    readonly VersionMeta: {
      readonly id: CodecTypes["idb/string@1"]["input"];
      readonly model: CodecTypes["idb/string@1"]["input"];
      readonly key: CodecTypes["idb/json@1"]["input"];
      readonly lastAppliedChangeId: CodecTypes["idb/string@1"]["input"] | null;
      readonly localChangePending: CodecTypes["idb/bool@1"]["input"];
    };
  };
};
export type TypeMaps = IdbTypeMaps<CodecTypes, FieldOutputTypes, FieldInputTypes>;

type ContractBase = Omit<
  ContractType<{
    readonly stores: {
      readonly _idb_sync_outbox: {
        readonly keyPath: "id";
        readonly indexes: {
          readonly byCreatedAt: { readonly keyPath: "createdAt"; readonly unique: false };
        };
      };
      readonly _idb_sync_version_meta: {
        readonly keyPath: "id";
        readonly indexes: Record<string, never>;
      };
    };
    readonly namespaces: {
      readonly __unbound__: { readonly id: "__unbound__"; readonly entries: Record<string, never> };
    };
    readonly storageHash: StorageHash;
  }>,
  "roots" | "domain"
> & {
  readonly target: "idb";
  readonly targetFamily: "idb";
  readonly roots: {
    readonly _idb_sync_outbox: {
      readonly namespace: "__unbound__" & NamespaceId;
      readonly model: "OutboxEvent";
    };
    readonly _idb_sync_version_meta: {
      readonly namespace: "__unbound__" & NamespaceId;
      readonly model: "VersionMeta";
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly __unbound__: {
        readonly models: {
          readonly OutboxEvent: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
              };
              readonly entityType: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
              };
              readonly operation: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
              };
              readonly payload: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/json@1" };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/date@1" };
              };
              readonly synced: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/bool@1" };
              };
              readonly syncedAt: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/date@1" };
              };
              readonly lastAttemptedAt: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/date@1" };
              };
              readonly tries: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/int32@1" };
              };
              readonly lastError: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
              };
              readonly retryable: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/bool@1" };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly storeName: "_idb_sync_outbox"; readonly keyPath: "id" };
          };
          readonly VersionMeta: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
              };
              readonly model: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
              };
              readonly key: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/json@1" };
              };
              readonly lastAppliedChangeId: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/string@1" };
              };
              readonly localChangePending: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "idb/bool@1" };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly storeName: "_idb_sync_version_meta";
              readonly keyPath: "id";
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly idb: {
      readonly compoundKeys: false;
      readonly ddlOnlyInUpgrade: true;
      readonly returning: false;
      readonly transactionalDDL: true;
    };
  };
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = IdbContractWithTypeMaps<ContractBase, TypeMaps>;

export type Stores = Contract["storage"]["stores"];
