// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from "@prisma/orm-postgres/target/codec-types";
import type { QueryOperationTypes as PgTargetQueryOps } from "@prisma/orm-postgres/target/operation-types";

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from "@prisma/orm-postgres/family-contract/types";
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from "@prisma/orm-postgres/contract/types";

export type StorageHash = StorageHashBase<"409c2d98e5372ee1ecbc0ba5076f2be78ac2a95d834e35ad25600732d6e2c3fc">;
export type ExecutionHash = ExecutionHashBase<"bec6305326b570a7250d923bf8ee32069321872a447fc6a71816854c76e8c098">;
export type ProfileHash = ProfileHashBase<"3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2">;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgTargetQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly "pg/float@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/float4@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/float8@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/int@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/int2@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/int4@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/int8@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/int8number@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/interval@1": { readonly output: "pg/interval@1"; readonly nullable: true };
      readonly "pg/numeric@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
      readonly "pg/time-string@1": { readonly output: "pg/interval@1"; readonly nullable: true };
      readonly "pg/time-temporal@1": { readonly output: "pg/interval@1"; readonly nullable: true };
      readonly "pg/unboundedint@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "sql/float@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "sql/int@1": { readonly output: "pg/float8@1"; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly "pg/int@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
      readonly "pg/int2@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
      readonly "pg/int4@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
      readonly "pg/int8@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
      readonly "pg/int8number@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
      readonly "pg/numeric@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
      readonly "pg/unboundedint@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
      readonly "sql/int@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: "pg/int8number@1"; readonly nullable: false };
    readonly anyInput: { readonly output: "pg/int8number@1"; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: "pg/int8@1"; readonly nullable: false };
    readonly anyInput: { readonly output: "pg/int8@1"; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly "pg/char@1": { readonly output: "pg/char@1"; readonly nullable: true };
      readonly "pg/date-string@1": { readonly output: "pg/date-string@1"; readonly nullable: true };
      readonly "pg/date-temporal@1": {
        readonly output: "pg/date-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/enum@1": { readonly output: "pg/enum@1"; readonly nullable: true };
      readonly "pg/float@1": { readonly output: "pg/float@1"; readonly nullable: true };
      readonly "pg/float4@1": { readonly output: "pg/float4@1"; readonly nullable: true };
      readonly "pg/float8@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/inet@1": { readonly output: "pg/inet@1"; readonly nullable: true };
      readonly "pg/int@1": { readonly output: "pg/int@1"; readonly nullable: true };
      readonly "pg/int2@1": { readonly output: "pg/int2@1"; readonly nullable: true };
      readonly "pg/int4@1": { readonly output: "pg/int4@1"; readonly nullable: true };
      readonly "pg/int8@1": { readonly output: "pg/int8@1"; readonly nullable: true };
      readonly "pg/int8number@1": { readonly output: "pg/int8number@1"; readonly nullable: true };
      readonly "pg/interval@1": { readonly output: "pg/interval@1"; readonly nullable: true };
      readonly "pg/numeric@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
      readonly "pg/text-array@1": { readonly output: "pg/text-array@1"; readonly nullable: true };
      readonly "pg/text@1": { readonly output: "pg/text@1"; readonly nullable: true };
      readonly "pg/time-string@1": { readonly output: "pg/time-string@1"; readonly nullable: true };
      readonly "pg/time-temporal@1": {
        readonly output: "pg/time-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timestamp-string@1": {
        readonly output: "pg/timestamp-string@1";
        readonly nullable: true;
      };
      readonly "pg/timestamp-temporal@1": {
        readonly output: "pg/timestamp-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-date@1": {
        readonly output: "pg/timestamptz-date@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-string@1": {
        readonly output: "pg/timestamptz-string@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-temporal@1": {
        readonly output: "pg/timestamptz-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timetz@1": { readonly output: "pg/timetz@1"; readonly nullable: true };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "pg/varchar@1": { readonly output: "pg/text@1"; readonly nullable: true };
      readonly "sql/char@1": { readonly output: "sql/char@1"; readonly nullable: true };
      readonly "sql/float@1": { readonly output: "sql/float@1"; readonly nullable: true };
      readonly "sql/int@1": { readonly output: "sql/int@1"; readonly nullable: true };
      readonly "sql/text@1": { readonly output: "sql/text@1"; readonly nullable: true };
      readonly "sql/varchar@1": { readonly output: "pg/text@1"; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly "pg/char@1": { readonly output: "pg/char@1"; readonly nullable: true };
      readonly "pg/date-string@1": { readonly output: "pg/date-string@1"; readonly nullable: true };
      readonly "pg/date-temporal@1": {
        readonly output: "pg/date-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/enum@1": { readonly output: "pg/enum@1"; readonly nullable: true };
      readonly "pg/float@1": { readonly output: "pg/float@1"; readonly nullable: true };
      readonly "pg/float4@1": { readonly output: "pg/float4@1"; readonly nullable: true };
      readonly "pg/float8@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/inet@1": { readonly output: "pg/inet@1"; readonly nullable: true };
      readonly "pg/int@1": { readonly output: "pg/int@1"; readonly nullable: true };
      readonly "pg/int2@1": { readonly output: "pg/int2@1"; readonly nullable: true };
      readonly "pg/int4@1": { readonly output: "pg/int4@1"; readonly nullable: true };
      readonly "pg/int8@1": { readonly output: "pg/int8@1"; readonly nullable: true };
      readonly "pg/int8number@1": { readonly output: "pg/int8number@1"; readonly nullable: true };
      readonly "pg/interval@1": { readonly output: "pg/interval@1"; readonly nullable: true };
      readonly "pg/numeric@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
      readonly "pg/text-array@1": { readonly output: "pg/text-array@1"; readonly nullable: true };
      readonly "pg/text@1": { readonly output: "pg/text@1"; readonly nullable: true };
      readonly "pg/time-string@1": { readonly output: "pg/time-string@1"; readonly nullable: true };
      readonly "pg/time-temporal@1": {
        readonly output: "pg/time-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timestamp-string@1": {
        readonly output: "pg/timestamp-string@1";
        readonly nullable: true;
      };
      readonly "pg/timestamp-temporal@1": {
        readonly output: "pg/timestamp-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-date@1": {
        readonly output: "pg/timestamptz-date@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-string@1": {
        readonly output: "pg/timestamptz-string@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-temporal@1": {
        readonly output: "pg/timestamptz-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timetz@1": { readonly output: "pg/timetz@1"; readonly nullable: true };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "pg/varchar@1": { readonly output: "pg/text@1"; readonly nullable: true };
      readonly "sql/char@1": { readonly output: "sql/char@1"; readonly nullable: true };
      readonly "sql/float@1": { readonly output: "sql/float@1"; readonly nullable: true };
      readonly "sql/int@1": { readonly output: "sql/int@1"; readonly nullable: true };
      readonly "sql/text@1": { readonly output: "sql/text@1"; readonly nullable: true };
      readonly "sql/varchar@1": { readonly output: "pg/text@1"; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly "pg/float@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/float4@1": { readonly output: "pg/float4@1"; readonly nullable: true };
      readonly "pg/float8@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/int@1": { readonly output: "pg/int8number@1"; readonly nullable: true };
      readonly "pg/int2@1": { readonly output: "pg/int8number@1"; readonly nullable: true };
      readonly "pg/int4@1": { readonly output: "pg/int8number@1"; readonly nullable: true };
      readonly "pg/int8@1": { readonly output: "pg/int8number@1"; readonly nullable: true };
      readonly "pg/int8number@1": { readonly output: "pg/int8number@1"; readonly nullable: true };
      readonly "pg/interval@1": { readonly output: "pg/interval@1"; readonly nullable: true };
      readonly "pg/numeric@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
      readonly "pg/time-string@1": { readonly output: "pg/interval@1"; readonly nullable: true };
      readonly "pg/time-temporal@1": { readonly output: "pg/interval@1"; readonly nullable: true };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "sql/float@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "sql/int@1": { readonly output: "pg/int8number@1"; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly "pg/int@1": { readonly output: "pg/int8@1"; readonly nullable: true };
      readonly "pg/int2@1": { readonly output: "pg/int8@1"; readonly nullable: true };
      readonly "pg/int4@1": { readonly output: "pg/int8@1"; readonly nullable: true };
      readonly "pg/int8@1": { readonly output: "pg/unboundedint@1"; readonly nullable: true };
      readonly "pg/int8number@1": { readonly output: "pg/unboundedint@1"; readonly nullable: true };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "sql/int@1": { readonly output: "pg/int8@1"; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]["json"]
    ? Encoded
    : CodecTypes[CodecId]["json"]
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Account: {
      readonly accessToken: CodecTypes["pg/text@1"]["output"] | null;
      readonly accessTokenExpiresAt: CodecTypes["pg/timestamptz-date@1"]["output"] | null;
      readonly accountId: CodecTypes["pg/text@1"]["output"];
      readonly createdAt: CodecTypes["pg/timestamptz-date@1"]["output"];
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly idToken: CodecTypes["pg/text@1"]["output"] | null;
      readonly password: CodecTypes["pg/text@1"]["output"] | null;
      readonly providerId: CodecTypes["pg/text@1"]["output"];
      readonly refreshToken: CodecTypes["pg/text@1"]["output"] | null;
      readonly refreshTokenExpiresAt: CodecTypes["pg/timestamptz-date@1"]["output"] | null;
      readonly scope: CodecTypes["pg/text@1"]["output"] | null;
      readonly updatedAt: CodecTypes["pg/timestamptz-date@1"]["output"];
      readonly userId: CodecTypes["pg/text@1"]["output"];
    };
    readonly AuditLog: {
      readonly action: CodecTypes["pg/text@1"]["output"];
      readonly createdAt: CodecTypes["pg/timestamptz-date@1"]["output"];
      readonly id: CodecTypes["pg/text@1"]["output"];
    };
    readonly Board: {
      readonly createdAt: CodecTypes["pg/timestamptz-date@1"]["output"];
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly name: CodecTypes["pg/text@1"]["output"];
      readonly userId: CodecTypes["pg/text@1"]["output"];
    };
    readonly Changelog: {
      readonly createdAt: CodecTypes["pg/timestamptz-date@1"]["output"];
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly keyPath: CodecTypes["pg/text@1"]["output"];
      readonly model: CodecTypes["pg/text@1"]["output"];
      readonly operation: "create" | "update" | "delete";
      readonly outboxEventId: CodecTypes["pg/text@1"]["output"];
      readonly scopeKey: CodecTypes["pg/text@1"]["output"];
    };
    readonly Session: {
      readonly createdAt: CodecTypes["pg/timestamptz-date@1"]["output"];
      readonly expiresAt: CodecTypes["pg/timestamptz-date@1"]["output"];
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly ipAddress: CodecTypes["pg/text@1"]["output"] | null;
      readonly token: CodecTypes["pg/text@1"]["output"];
      readonly updatedAt: CodecTypes["pg/timestamptz-date@1"]["output"];
      readonly userAgent: CodecTypes["pg/text@1"]["output"] | null;
      readonly userId: CodecTypes["pg/text@1"]["output"];
    };
    readonly Todo: {
      readonly boardId: CodecTypes["pg/text@1"]["output"];
      readonly createdAt: CodecTypes["pg/timestamptz-date@1"]["output"];
      readonly description: CodecTypes["pg/text@1"]["output"] | null;
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly isCompleted: CodecTypes["pg/bool@1"]["output"];
      readonly title: CodecTypes["pg/text@1"]["output"];
    };
    readonly User: {
      readonly createdAt: CodecTypes["pg/timestamptz-date@1"]["output"];
      readonly email: CodecTypes["pg/text@1"]["output"];
      readonly emailVerified: CodecTypes["pg/bool@1"]["output"];
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly image: CodecTypes["pg/text@1"]["output"] | null;
      readonly isAnonymous: CodecTypes["pg/bool@1"]["output"];
      readonly name: CodecTypes["pg/text@1"]["output"];
      readonly updatedAt: CodecTypes["pg/timestamptz-date@1"]["output"];
    };
    readonly Verification: {
      readonly createdAt: CodecTypes["pg/timestamptz-date@1"]["output"];
      readonly expiresAt: CodecTypes["pg/timestamptz-date@1"]["output"];
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly identifier: CodecTypes["pg/text@1"]["output"];
      readonly updatedAt: CodecTypes["pg/timestamptz-date@1"]["output"];
      readonly value: CodecTypes["pg/text@1"]["output"];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Account: {
      readonly accessToken: CodecTypes["pg/text@1"]["input"] | null;
      readonly accessTokenExpiresAt: CodecTypes["pg/timestamptz-date@1"]["input"] | null;
      readonly accountId: CodecTypes["pg/text@1"]["input"];
      readonly createdAt: CodecTypes["pg/timestamptz-date@1"]["input"];
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly idToken: CodecTypes["pg/text@1"]["input"] | null;
      readonly password: CodecTypes["pg/text@1"]["input"] | null;
      readonly providerId: CodecTypes["pg/text@1"]["input"];
      readonly refreshToken: CodecTypes["pg/text@1"]["input"] | null;
      readonly refreshTokenExpiresAt: CodecTypes["pg/timestamptz-date@1"]["input"] | null;
      readonly scope: CodecTypes["pg/text@1"]["input"] | null;
      readonly updatedAt: CodecTypes["pg/timestamptz-date@1"]["input"];
      readonly userId: CodecTypes["pg/text@1"]["input"];
    };
    readonly AuditLog: {
      readonly action: CodecTypes["pg/text@1"]["input"];
      readonly createdAt: CodecTypes["pg/timestamptz-date@1"]["input"];
      readonly id: CodecTypes["pg/text@1"]["input"];
    };
    readonly Board: {
      readonly createdAt: CodecTypes["pg/timestamptz-date@1"]["input"];
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly name: CodecTypes["pg/text@1"]["input"];
      readonly userId: CodecTypes["pg/text@1"]["input"];
    };
    readonly Changelog: {
      readonly createdAt: CodecTypes["pg/timestamptz-date@1"]["input"];
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly keyPath: CodecTypes["pg/text@1"]["input"];
      readonly model: CodecTypes["pg/text@1"]["input"];
      readonly operation: "create" | "update" | "delete";
      readonly outboxEventId: CodecTypes["pg/text@1"]["input"];
      readonly scopeKey: CodecTypes["pg/text@1"]["input"];
    };
    readonly Session: {
      readonly createdAt: CodecTypes["pg/timestamptz-date@1"]["input"];
      readonly expiresAt: CodecTypes["pg/timestamptz-date@1"]["input"];
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly ipAddress: CodecTypes["pg/text@1"]["input"] | null;
      readonly token: CodecTypes["pg/text@1"]["input"];
      readonly updatedAt: CodecTypes["pg/timestamptz-date@1"]["input"];
      readonly userAgent: CodecTypes["pg/text@1"]["input"] | null;
      readonly userId: CodecTypes["pg/text@1"]["input"];
    };
    readonly Todo: {
      readonly boardId: CodecTypes["pg/text@1"]["input"];
      readonly createdAt: CodecTypes["pg/timestamptz-date@1"]["input"];
      readonly description: CodecTypes["pg/text@1"]["input"] | null;
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly isCompleted: CodecTypes["pg/bool@1"]["input"];
      readonly title: CodecTypes["pg/text@1"]["input"];
    };
    readonly User: {
      readonly createdAt: CodecTypes["pg/timestamptz-date@1"]["input"];
      readonly email: CodecTypes["pg/text@1"]["input"];
      readonly emailVerified: CodecTypes["pg/bool@1"]["input"];
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly image: CodecTypes["pg/text@1"]["input"] | null;
      readonly isAnonymous: CodecTypes["pg/bool@1"]["input"];
      readonly name: CodecTypes["pg/text@1"]["input"];
      readonly updatedAt: CodecTypes["pg/timestamptz-date@1"]["input"];
    };
    readonly Verification: {
      readonly createdAt: CodecTypes["pg/timestamptz-date@1"]["input"];
      readonly expiresAt: CodecTypes["pg/timestamptz-date@1"]["input"];
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly identifier: CodecTypes["pg/text@1"]["input"];
      readonly updatedAt: CodecTypes["pg/timestamptz-date@1"]["input"];
      readonly value: CodecTypes["pg/text@1"]["input"];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly account: {
      readonly accessToken: CodecTypes["pg/text@1"]["output"] | null;
      readonly accessTokenExpiresAt: CodecTypes["pg/timestamptz-date@1"]["output"] | null;
      readonly accountId: CodecTypes["pg/text@1"]["output"];
      readonly createdAt: CodecTypes["pg/timestamptz-date@1"]["output"];
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly idToken: CodecTypes["pg/text@1"]["output"] | null;
      readonly password: CodecTypes["pg/text@1"]["output"] | null;
      readonly providerId: CodecTypes["pg/text@1"]["output"];
      readonly refreshToken: CodecTypes["pg/text@1"]["output"] | null;
      readonly refreshTokenExpiresAt: CodecTypes["pg/timestamptz-date@1"]["output"] | null;
      readonly scope: CodecTypes["pg/text@1"]["output"] | null;
      readonly updatedAt: CodecTypes["pg/timestamptz-date@1"]["output"];
      readonly userId: CodecTypes["pg/text@1"]["output"];
    };
    readonly AuditLog: {
      readonly action: CodecTypes["pg/text@1"]["output"];
      readonly createdAt: CodecTypes["pg/timestamptz-date@1"]["output"];
      readonly id: CodecTypes["pg/text@1"]["output"];
    };
    readonly Board: {
      readonly createdAt: CodecTypes["pg/timestamptz-date@1"]["output"];
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly name: CodecTypes["pg/text@1"]["output"];
      readonly userId: CodecTypes["pg/text@1"]["output"];
    };
    readonly Changelog: {
      readonly createdAt: CodecTypes["pg/timestamptz-date@1"]["output"];
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly keyPath: CodecTypes["pg/text@1"]["output"];
      readonly model: CodecTypes["pg/text@1"]["output"];
      readonly operation: "create" | "update" | "delete";
      readonly outboxEventId: CodecTypes["pg/text@1"]["output"];
      readonly scopeKey: CodecTypes["pg/text@1"]["output"];
    };
    readonly session: {
      readonly createdAt: CodecTypes["pg/timestamptz-date@1"]["output"];
      readonly expiresAt: CodecTypes["pg/timestamptz-date@1"]["output"];
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly ipAddress: CodecTypes["pg/text@1"]["output"] | null;
      readonly token: CodecTypes["pg/text@1"]["output"];
      readonly updatedAt: CodecTypes["pg/timestamptz-date@1"]["output"];
      readonly userAgent: CodecTypes["pg/text@1"]["output"] | null;
      readonly userId: CodecTypes["pg/text@1"]["output"];
    };
    readonly Todo: {
      readonly boardId: CodecTypes["pg/text@1"]["output"];
      readonly createdAt: CodecTypes["pg/timestamptz-date@1"]["output"];
      readonly description: CodecTypes["pg/text@1"]["output"] | null;
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly isCompleted: CodecTypes["pg/bool@1"]["output"];
      readonly title: CodecTypes["pg/text@1"]["output"];
    };
    readonly user: {
      readonly createdAt: CodecTypes["pg/timestamptz-date@1"]["output"];
      readonly email: CodecTypes["pg/text@1"]["output"];
      readonly emailVerified: CodecTypes["pg/bool@1"]["output"];
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly image: CodecTypes["pg/text@1"]["output"] | null;
      readonly isAnonymous: CodecTypes["pg/bool@1"]["output"];
      readonly name: CodecTypes["pg/text@1"]["output"];
      readonly updatedAt: CodecTypes["pg/timestamptz-date@1"]["output"];
    };
    readonly verification: {
      readonly createdAt: CodecTypes["pg/timestamptz-date@1"]["output"];
      readonly expiresAt: CodecTypes["pg/timestamptz-date@1"]["output"];
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly identifier: CodecTypes["pg/text@1"]["output"];
      readonly updatedAt: CodecTypes["pg/timestamptz-date@1"]["output"];
      readonly value: CodecTypes["pg/text@1"]["output"];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly account: {
      readonly accessToken: CodecTypes["pg/text@1"]["input"] | null;
      readonly accessTokenExpiresAt: CodecTypes["pg/timestamptz-date@1"]["input"] | null;
      readonly accountId: CodecTypes["pg/text@1"]["input"];
      readonly createdAt: CodecTypes["pg/timestamptz-date@1"]["input"];
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly idToken: CodecTypes["pg/text@1"]["input"] | null;
      readonly password: CodecTypes["pg/text@1"]["input"] | null;
      readonly providerId: CodecTypes["pg/text@1"]["input"];
      readonly refreshToken: CodecTypes["pg/text@1"]["input"] | null;
      readonly refreshTokenExpiresAt: CodecTypes["pg/timestamptz-date@1"]["input"] | null;
      readonly scope: CodecTypes["pg/text@1"]["input"] | null;
      readonly updatedAt: CodecTypes["pg/timestamptz-date@1"]["input"];
      readonly userId: CodecTypes["pg/text@1"]["input"];
    };
    readonly AuditLog: {
      readonly action: CodecTypes["pg/text@1"]["input"];
      readonly createdAt: CodecTypes["pg/timestamptz-date@1"]["input"];
      readonly id: CodecTypes["pg/text@1"]["input"];
    };
    readonly Board: {
      readonly createdAt: CodecTypes["pg/timestamptz-date@1"]["input"];
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly name: CodecTypes["pg/text@1"]["input"];
      readonly userId: CodecTypes["pg/text@1"]["input"];
    };
    readonly Changelog: {
      readonly createdAt: CodecTypes["pg/timestamptz-date@1"]["input"];
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly keyPath: CodecTypes["pg/text@1"]["input"];
      readonly model: CodecTypes["pg/text@1"]["input"];
      readonly operation: "create" | "update" | "delete";
      readonly outboxEventId: CodecTypes["pg/text@1"]["input"];
      readonly scopeKey: CodecTypes["pg/text@1"]["input"];
    };
    readonly session: {
      readonly createdAt: CodecTypes["pg/timestamptz-date@1"]["input"];
      readonly expiresAt: CodecTypes["pg/timestamptz-date@1"]["input"];
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly ipAddress: CodecTypes["pg/text@1"]["input"] | null;
      readonly token: CodecTypes["pg/text@1"]["input"];
      readonly updatedAt: CodecTypes["pg/timestamptz-date@1"]["input"];
      readonly userAgent: CodecTypes["pg/text@1"]["input"] | null;
      readonly userId: CodecTypes["pg/text@1"]["input"];
    };
    readonly Todo: {
      readonly boardId: CodecTypes["pg/text@1"]["input"];
      readonly createdAt: CodecTypes["pg/timestamptz-date@1"]["input"];
      readonly description: CodecTypes["pg/text@1"]["input"] | null;
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly isCompleted: CodecTypes["pg/bool@1"]["input"];
      readonly title: CodecTypes["pg/text@1"]["input"];
    };
    readonly user: {
      readonly createdAt: CodecTypes["pg/timestamptz-date@1"]["input"];
      readonly email: CodecTypes["pg/text@1"]["input"];
      readonly emailVerified: CodecTypes["pg/bool@1"]["input"];
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly image: CodecTypes["pg/text@1"]["input"] | null;
      readonly isAnonymous: CodecTypes["pg/bool@1"]["input"];
      readonly name: CodecTypes["pg/text@1"]["input"];
      readonly updatedAt: CodecTypes["pg/timestamptz-date@1"]["input"];
    };
    readonly verification: {
      readonly createdAt: CodecTypes["pg/timestamptz-date@1"]["input"];
      readonly expiresAt: CodecTypes["pg/timestamptz-date@1"]["input"];
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly identifier: CodecTypes["pg/text@1"]["input"];
      readonly updatedAt: CodecTypes["pg/timestamptz-date@1"]["input"];
      readonly value: CodecTypes["pg/text@1"]["input"];
    };
  };
};

export namespace Models {
  export type public_Account = {
    accessToken: CodecTypes["pg/text@1"]["output"] | null;
    accessTokenExpiresAt: CodecTypes["pg/timestamptz-date@1"]["output"] | null;
    accountId: CodecTypes["pg/text@1"]["output"];
    createdAt: CodecTypes["pg/timestamptz-date@1"]["output"];
    id: CodecTypes["pg/text@1"]["output"];
    idToken: CodecTypes["pg/text@1"]["output"] | null;
    password: CodecTypes["pg/text@1"]["output"] | null;
    providerId: CodecTypes["pg/text@1"]["output"];
    refreshToken: CodecTypes["pg/text@1"]["output"] | null;
    refreshTokenExpiresAt: CodecTypes["pg/timestamptz-date@1"]["output"] | null;
    scope: CodecTypes["pg/text@1"]["output"] | null;
    updatedAt: CodecTypes["pg/timestamptz-date@1"]["output"];
    userId: CodecTypes["pg/text@1"]["output"];
    user: public_User;
    readonly [RelationKeys]?: "user";
  };
  export type public_AuditLog = {
    action: CodecTypes["pg/text@1"]["output"];
    createdAt: CodecTypes["pg/timestamptz-date@1"]["output"];
    id: CodecTypes["pg/text@1"]["output"];
    readonly [RelationKeys]?: never;
  };
  export type public_Board = {
    createdAt: CodecTypes["pg/timestamptz-date@1"]["output"];
    id: CodecTypes["pg/text@1"]["output"];
    name: CodecTypes["pg/text@1"]["output"];
    userId: CodecTypes["pg/text@1"]["output"];
    todos: public_Todo[];
    user: public_User;
    readonly [RelationKeys]?: "todos" | "user";
  };
  export type public_Changelog = {
    createdAt: CodecTypes["pg/timestamptz-date@1"]["output"];
    id: CodecTypes["pg/text@1"]["output"];
    keyPath: CodecTypes["pg/text@1"]["output"];
    model: CodecTypes["pg/text@1"]["output"];
    operation: "create" | "update" | "delete";
    outboxEventId: CodecTypes["pg/text@1"]["output"];
    scopeKey: CodecTypes["pg/text@1"]["output"];
    readonly [RelationKeys]?: never;
  };
  export type public_Session = {
    createdAt: CodecTypes["pg/timestamptz-date@1"]["output"];
    expiresAt: CodecTypes["pg/timestamptz-date@1"]["output"];
    id: CodecTypes["pg/text@1"]["output"];
    ipAddress: CodecTypes["pg/text@1"]["output"] | null;
    token: CodecTypes["pg/text@1"]["output"];
    updatedAt: CodecTypes["pg/timestamptz-date@1"]["output"];
    userAgent: CodecTypes["pg/text@1"]["output"] | null;
    userId: CodecTypes["pg/text@1"]["output"];
    user: public_User;
    readonly [RelationKeys]?: "user";
  };
  export type public_Todo = {
    boardId: CodecTypes["pg/text@1"]["output"];
    createdAt: CodecTypes["pg/timestamptz-date@1"]["output"];
    description: CodecTypes["pg/text@1"]["output"] | null;
    id: CodecTypes["pg/text@1"]["output"];
    isCompleted: CodecTypes["pg/bool@1"]["output"];
    title: CodecTypes["pg/text@1"]["output"];
    board: public_Board;
    readonly [RelationKeys]?: "board";
  };
  export type public_User = {
    createdAt: CodecTypes["pg/timestamptz-date@1"]["output"];
    email: CodecTypes["pg/text@1"]["output"];
    emailVerified: CodecTypes["pg/bool@1"]["output"];
    id: CodecTypes["pg/text@1"]["output"];
    image: CodecTypes["pg/text@1"]["output"] | null;
    isAnonymous: CodecTypes["pg/bool@1"]["output"];
    name: CodecTypes["pg/text@1"]["output"];
    updatedAt: CodecTypes["pg/timestamptz-date@1"]["output"];
    accounts: public_Account[];
    boards: public_Board[];
    sessions: public_Session[];
    readonly [RelationKeys]?: "accounts" | "boards" | "sessions";
  };
  export type public_Verification = {
    createdAt: CodecTypes["pg/timestamptz-date@1"]["output"];
    expiresAt: CodecTypes["pg/timestamptz-date@1"]["output"];
    id: CodecTypes["pg/text@1"]["output"];
    identifier: CodecTypes["pg/text@1"]["output"];
    updatedAt: CodecTypes["pg/timestamptz-date@1"]["output"];
    value: CodecTypes["pg/text@1"]["output"];
    readonly [RelationKeys]?: never;
  };
}

export declare const models: {
  public: {
    Account: Models.public_Account;
    AuditLog: Models.public_AuditLog;
    Board: Models.public_Board;
    Changelog: Models.public_Changelog;
    Session: Models.public_Session;
    Todo: Models.public_Todo;
    User: Models.public_User;
    Verification: Models.public_Verification;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: "public";
        readonly kind: "postgres-schema";
        readonly entries: {
          readonly table: {
            readonly account: {
              columns: {
                readonly accessToken: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                };
                readonly accessTokenExpiresAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-date@1";
                  readonly nullable: true;
                };
                readonly accountId: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-date@1";
                  readonly nullable: false;
                  readonly default: { readonly kind: "function"; readonly expression: "now()" };
                };
                readonly id: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly idToken: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                };
                readonly password: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                };
                readonly providerId: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly refreshToken: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                };
                readonly refreshTokenExpiresAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-date@1";
                  readonly nullable: true;
                };
                readonly scope: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                };
                readonly updatedAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-date@1";
                  readonly nullable: false;
                };
                readonly userId: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [{ readonly columns: readonly ["providerId", "accountId"] }];
              indexes: readonly [
                {
                  readonly name: "account_userId_idx_a489d58a";
                  readonly prefix: "account_userId_idx";
                  readonly columns: readonly ["userId"];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "account";
                    readonly columns: readonly ["userId"];
                  };
                  readonly target: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "user";
                    readonly columns: readonly ["id"];
                  };
                },
              ];
            };
            readonly AuditLog: {
              columns: {
                readonly action: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-date@1";
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly Board: {
              columns: {
                readonly createdAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-date@1";
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly userId: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: "Board_userId_idx_a489d58a";
                  readonly prefix: "Board_userId_idx";
                  readonly columns: readonly ["userId"];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "Board";
                    readonly columns: readonly ["userId"];
                  };
                  readonly target: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "user";
                    readonly columns: readonly ["id"];
                  };
                },
              ];
            };
            readonly Changelog: {
              columns: {
                readonly createdAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-date@1";
                  readonly nullable: false;
                  readonly default: { readonly kind: "function"; readonly expression: "now()" };
                };
                readonly id: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly keyPath: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly model: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly operation: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly outboxEventId: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly scopeKey: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [{ readonly columns: readonly ["outboxEventId"] }];
              indexes: readonly [
                {
                  readonly name: "Changelog_scopeKey_id_idx_9635f6eb";
                  readonly prefix: "Changelog_scopeKey_id_idx";
                  readonly columns: readonly ["scopeKey", "id"];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [];
            };
            readonly session: {
              columns: {
                readonly createdAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-date@1";
                  readonly nullable: false;
                  readonly default: { readonly kind: "function"; readonly expression: "now()" };
                };
                readonly expiresAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-date@1";
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly ipAddress: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                };
                readonly token: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly updatedAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-date@1";
                  readonly nullable: false;
                };
                readonly userAgent: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                };
                readonly userId: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [{ readonly columns: readonly ["token"] }];
              indexes: readonly [
                {
                  readonly name: "session_userId_idx_a489d58a";
                  readonly prefix: "session_userId_idx";
                  readonly columns: readonly ["userId"];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "session";
                    readonly columns: readonly ["userId"];
                  };
                  readonly target: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "user";
                    readonly columns: readonly ["id"];
                  };
                },
              ];
            };
            readonly Todo: {
              columns: {
                readonly boardId: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-date@1";
                  readonly nullable: false;
                };
                readonly description: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                };
                readonly id: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly isCompleted: {
                  readonly nativeType: "bool";
                  readonly codecId: "pg/bool@1";
                  readonly nullable: false;
                };
                readonly title: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: "Todo_boardId_idx_74a7b59d";
                  readonly prefix: "Todo_boardId_idx";
                  readonly columns: readonly ["boardId"];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "Todo";
                    readonly columns: readonly ["boardId"];
                  };
                  readonly target: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "Board";
                    readonly columns: readonly ["id"];
                  };
                },
              ];
            };
            readonly user: {
              columns: {
                readonly createdAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-date@1";
                  readonly nullable: false;
                  readonly default: { readonly kind: "function"; readonly expression: "now()" };
                };
                readonly email: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly emailVerified: {
                  readonly nativeType: "bool";
                  readonly codecId: "pg/bool@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "literal";
                    readonly value: DefaultLiteralValue<"pg/bool@1", false>;
                  };
                };
                readonly id: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly image: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                };
                readonly isAnonymous: {
                  readonly nativeType: "bool";
                  readonly codecId: "pg/bool@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "literal";
                    readonly value: DefaultLiteralValue<"pg/bool@1", false>;
                  };
                };
                readonly name: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly updatedAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-date@1";
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [{ readonly columns: readonly ["email"] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly verification: {
              columns: {
                readonly createdAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-date@1";
                  readonly nullable: false;
                  readonly default: { readonly kind: "function"; readonly expression: "now()" };
                };
                readonly expiresAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-date@1";
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly identifier: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly updatedAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-date@1";
                  readonly nullable: false;
                };
                readonly value: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
          readonly valueSet: {
            readonly ChangeOperation: {
              readonly kind: "valueSet";
              readonly values: readonly ["create", "update", "delete"];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  "roots" | "domain"
> & {
  readonly target: "postgres";
  readonly targetFamily: "sql";
  readonly roots: {
    readonly AuditLog: { readonly namespace: "public" & NamespaceId; readonly model: "AuditLog" };
    readonly Board: { readonly namespace: "public" & NamespaceId; readonly model: "Board" };
    readonly Changelog: { readonly namespace: "public" & NamespaceId; readonly model: "Changelog" };
    readonly Todo: { readonly namespace: "public" & NamespaceId; readonly model: "Todo" };
    readonly account: { readonly namespace: "public" & NamespaceId; readonly model: "Account" };
    readonly session: { readonly namespace: "public" & NamespaceId; readonly model: "Session" };
    readonly user: { readonly namespace: "public" & NamespaceId; readonly model: "User" };
    readonly verification: {
      readonly namespace: "public" & NamespaceId;
      readonly model: "Verification";
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Account: {
            readonly fields: {
              readonly accessToken: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly accessTokenExpiresAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-date@1";
                };
              };
              readonly accountId: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-date@1";
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly idToken: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly password: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly providerId: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly refreshToken: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly refreshTokenExpiresAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-date@1";
                };
              };
              readonly scope: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-date@1";
                };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
            };
            readonly relations: {
              readonly user: {
                readonly to: { readonly namespace: "public" & NamespaceId; readonly model: "User" };
                readonly cardinality: "N:1";
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ["userId"];
                  readonly targetFields: readonly ["id"];
                };
              };
            };
            readonly storage: {
              readonly table: "account";
              readonly namespaceId: "public";
              readonly fields: {
                readonly accessToken: { readonly column: "accessToken" };
                readonly accessTokenExpiresAt: { readonly column: "accessTokenExpiresAt" };
                readonly accountId: { readonly column: "accountId" };
                readonly createdAt: { readonly column: "createdAt" };
                readonly id: { readonly column: "id" };
                readonly idToken: { readonly column: "idToken" };
                readonly password: { readonly column: "password" };
                readonly providerId: { readonly column: "providerId" };
                readonly refreshToken: { readonly column: "refreshToken" };
                readonly refreshTokenExpiresAt: { readonly column: "refreshTokenExpiresAt" };
                readonly scope: { readonly column: "scope" };
                readonly updatedAt: { readonly column: "updatedAt" };
                readonly userId: { readonly column: "userId" };
              };
            };
          };
          readonly AuditLog: {
            readonly fields: {
              readonly action: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-date@1";
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: "AuditLog";
              readonly namespaceId: "public";
              readonly fields: {
                readonly action: { readonly column: "action" };
                readonly createdAt: { readonly column: "createdAt" };
                readonly id: { readonly column: "id" };
              };
            };
          };
          readonly Board: {
            readonly fields: {
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-date@1";
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
            };
            readonly relations: {
              readonly todos: {
                readonly to: { readonly namespace: "public" & NamespaceId; readonly model: "Todo" };
                readonly cardinality: "1:N";
                readonly on: {
                  readonly localFields: readonly ["id"];
                  readonly targetFields: readonly ["boardId"];
                };
              };
              readonly user: {
                readonly to: { readonly namespace: "public" & NamespaceId; readonly model: "User" };
                readonly cardinality: "N:1";
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ["userId"];
                  readonly targetFields: readonly ["id"];
                };
              };
            };
            readonly storage: {
              readonly table: "Board";
              readonly namespaceId: "public";
              readonly fields: {
                readonly createdAt: { readonly column: "createdAt" };
                readonly id: { readonly column: "id" };
                readonly name: { readonly column: "name" };
                readonly userId: { readonly column: "userId" };
              };
            };
          };
          readonly Changelog: {
            readonly fields: {
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-date@1";
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly keyPath: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly model: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly operation: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly outboxEventId: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly scopeKey: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: "Changelog";
              readonly namespaceId: "public";
              readonly fields: {
                readonly createdAt: { readonly column: "createdAt" };
                readonly id: { readonly column: "id" };
                readonly keyPath: { readonly column: "keyPath" };
                readonly model: { readonly column: "model" };
                readonly operation: { readonly column: "operation" };
                readonly outboxEventId: { readonly column: "outboxEventId" };
                readonly scopeKey: { readonly column: "scopeKey" };
              };
            };
          };
          readonly Session: {
            readonly fields: {
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-date@1";
                };
              };
              readonly expiresAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-date@1";
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly ipAddress: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly token: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-date@1";
                };
              };
              readonly userAgent: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
            };
            readonly relations: {
              readonly user: {
                readonly to: { readonly namespace: "public" & NamespaceId; readonly model: "User" };
                readonly cardinality: "N:1";
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ["userId"];
                  readonly targetFields: readonly ["id"];
                };
              };
            };
            readonly storage: {
              readonly table: "session";
              readonly namespaceId: "public";
              readonly fields: {
                readonly createdAt: { readonly column: "createdAt" };
                readonly expiresAt: { readonly column: "expiresAt" };
                readonly id: { readonly column: "id" };
                readonly ipAddress: { readonly column: "ipAddress" };
                readonly token: { readonly column: "token" };
                readonly updatedAt: { readonly column: "updatedAt" };
                readonly userAgent: { readonly column: "userAgent" };
                readonly userId: { readonly column: "userId" };
              };
            };
          };
          readonly Todo: {
            readonly fields: {
              readonly boardId: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-date@1";
                };
              };
              readonly description: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly isCompleted: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/bool@1" };
              };
              readonly title: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
            };
            readonly relations: {
              readonly board: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "Board";
                };
                readonly cardinality: "N:1";
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ["boardId"];
                  readonly targetFields: readonly ["id"];
                };
              };
            };
            readonly storage: {
              readonly table: "Todo";
              readonly namespaceId: "public";
              readonly fields: {
                readonly boardId: { readonly column: "boardId" };
                readonly createdAt: { readonly column: "createdAt" };
                readonly description: { readonly column: "description" };
                readonly id: { readonly column: "id" };
                readonly isCompleted: { readonly column: "isCompleted" };
                readonly title: { readonly column: "title" };
              };
            };
          };
          readonly User: {
            readonly fields: {
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-date@1";
                };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly emailVerified: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/bool@1" };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly image: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly isAnonymous: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/bool@1" };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-date@1";
                };
              };
            };
            readonly relations: {
              readonly accounts: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "Account";
                };
                readonly cardinality: "1:N";
                readonly on: {
                  readonly localFields: readonly ["id"];
                  readonly targetFields: readonly ["userId"];
                };
              };
              readonly boards: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "Board";
                };
                readonly cardinality: "1:N";
                readonly on: {
                  readonly localFields: readonly ["id"];
                  readonly targetFields: readonly ["userId"];
                };
              };
              readonly sessions: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "Session";
                };
                readonly cardinality: "1:N";
                readonly on: {
                  readonly localFields: readonly ["id"];
                  readonly targetFields: readonly ["userId"];
                };
              };
            };
            readonly storage: {
              readonly table: "user";
              readonly namespaceId: "public";
              readonly fields: {
                readonly createdAt: { readonly column: "createdAt" };
                readonly email: { readonly column: "email" };
                readonly emailVerified: { readonly column: "emailVerified" };
                readonly id: { readonly column: "id" };
                readonly image: { readonly column: "image" };
                readonly isAnonymous: { readonly column: "isAnonymous" };
                readonly name: { readonly column: "name" };
                readonly updatedAt: { readonly column: "updatedAt" };
              };
            };
          };
          readonly Verification: {
            readonly fields: {
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-date@1";
                };
              };
              readonly expiresAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-date@1";
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly identifier: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-date@1";
                };
              };
              readonly value: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: "verification";
              readonly namespaceId: "public";
              readonly fields: {
                readonly createdAt: { readonly column: "createdAt" };
                readonly expiresAt: { readonly column: "expiresAt" };
                readonly id: { readonly column: "id" };
                readonly identifier: { readonly column: "identifier" };
                readonly updatedAt: { readonly column: "updatedAt" };
                readonly value: { readonly column: "value" };
              };
            };
          };
        };
        readonly enum: {
          readonly ChangeOperation: {
            readonly codecId: "pg/text@1";
            readonly members: readonly [
              { readonly name: "create"; readonly value: "create" },
              { readonly name: "update"; readonly value: "update" },
              { readonly name: "delete"; readonly value: "delete" },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly insertOnConflictSkip: true;
      readonly insertOnConflictWithoutTarget: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly onCreate: { readonly id: "uuidv7"; readonly kind: "generator" };
          readonly ref: {
            readonly column: "id";
            readonly namespace: "public";
            readonly table: "Changelog";
          };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract["storage"]["namespaces"];
